[package]
name        = "bip_peer"
version     = "0.0.1"
description = "Communication with bittorrent peers via peer wire protocol"

authors     = ["Andrew <amiller4421@gmail.com>"]

homepage    = "https://github.com/GGist/bip-rs/bip_peer"
repository  = "https://github.com/GGist/bip-rs/bip_peer"

keywords    = ["peer", "wire", "protocol", "pwp", "bittorrent"]

license     = "MIT/Apache-2.0"

[features]
unstable = []