[package]
name          = "bip_handshake"
version       = "0.1.4"
description   = "Common handshaking interface as well as a default handshake implementation"

authors       = ["Andrew <amiller4421@gmail.com>"]

homepage      = "https://github.com/GGist/bip-rs"
repository    = "https://github.com/GGist/bip-rs/tree/master/bip_handshake"
documentation = "http://ggist.github.io/bip-rs/bip_handshake/index.html"

keywords      = ["handshake", "bittorrent"]

license       = "MIT/Apache-2.0"

[dependencies]
bip_util    = { path = "../bip_util", version = "0.2.0" }
mio         = { git = "https://github.com/GGist/mio", branch = "win-fix-oneshot" }
bytes       = "0.3.0"
log         = "0.3.0"
slab        = { git = "https://github.com/carllerche/slab", rev = "36c635b313" }

[features]
unstable    = []